name: Python Matrix Strategy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}  # Dynamically select OS based on matrix

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # OS matrix
        python-version: [3.9, 3.10, 3.11, 3.12]  # Python version matrix

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Ensures the code is available

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}  # Install Python dynamically
          architecture: x64  # Ensure compatibility on macOS

      - name: Check Python Version
        run: python --version || python3 --version  # Verify installation
