name: Python Matrix Setup

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os-version }}

    strategy:
      matrix:
        os-version: [ ubuntu-latest , macos-latest, windows-latest]

    steps:
        - name: Checkout code
          uses: actions/setup-python@v4
          with:
            python-version: '3.9' 
        - name: Check Python3 version
          run: python3 --version
